on:
  push:
    branches:
      - master
    paths:
      - scripts/docker/corretto-slim/**
      - .github/workflows/docker-build-corretto-slim.yml

jobs:
  build-corretto:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.CONTAINER_REGISTRY_TOKEN }} | docker login ghcr.io -u anuraaga --password-stdin
      - name: Build docker image
        run: docker build -t ghcr.io/amazoncorretto-distroless:alpha .
        working-directory: scripts/docker/corretto-slim
      - name: Push docker image
        run: docker push ghcr.io/amazoncorretto-distroless:alpha
