on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v2
      # Safe to run on PR builds since only has read permissions.
      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository }} --password-stdin
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with Gradle
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: build
